
name: 01 - Building Blocks
on: [push, workflow_dispatch]
jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
    - name: Say Hello
      run: echo "Hello, World!"
  echo-goodbyye:
    runs-on: ubuntu-latest
    steps:
    - name: successful step
      run: |
        echo "I will pass"
        exit 0
    - name: Say goodbye
      run: echo "Goodbye!"

      

