name: 17 - 1 - Custom Actions - JS
run-name: 17 - 1 - Custom Actions - JS
on:
    workflow_dispatch:

jobs:
    dependency-update:
        runs-on: ubuntu-latest
        steps:
            - name: code checkout
              uses: actions/checkout@v3

            - name: Check for Dependencies update
              uses: ./.github/actions/js-dependency-update
            

